export const CLIENTS_SUCCESS = 'CLIENTS_SUCCESS';
export const CLIENTS_LOADING = 'CLIENTS_LOADING';
export const CLIENTS_FAILURE = 'CLIENTS_FAILURE';
export const CLIENTS_ADDED = 'CLIENTS_ADDED';
