export const ACCOUNT_SUCCESS = 'ACCOUNT_SUCCESS';
export const ACCOUNT_LOADING = 'ACCOUNT_LOADING';
export const ACCOUNT_FAILURE = 'ACCOUNT_FAILURE';
export const ACCOUNT_ADDED = 'ACCOUNT_ADDED';
